import * as THREE from 'three';
export const CAMERA_DEFAULTS={height:1.05,distance:1.4,fov:52,orbit:0,zoom:1,eyeHeight:.16,lookPitch:-.5};
export const CAMERA_LIMITS={height:[.35,2.5],distance:[.55,3],fov:[35,85],orbit:[-Math.PI,Math.PI],zoom:[.65,2],eyeHeight:[.10,.32],lookPitch:[-.7,.35]};
const STORAGE='hyperdrive.camera.v2';
export function sanitizeCamera(values={}){return Object.fromEntries(Object.entries(CAMERA_DEFAULTS).map(([k,v])=>[k,Number.isFinite(values[k])?Math.max(CAMERA_LIMITS[k][0],Math.min(CAMERA_LIMITS[k][1],values[k])):v]));}
export function createCameras(host,world,RAPIER){
 let settings;try{settings=sanitizeCamera(JSON.parse(localStorage.getItem(STORAGE)||'{}'));}catch{settings={...CAMERA_DEFAULTS};}
 const perspective=new THREE.PerspectiveCamera(settings.fov,1,.015,40),overhead=new THREE.OrthographicCamera(-2,2,2,-2,.01,40);
 overhead.position.set(0,8,0);overhead.up.set(0,0,1);overhead.lookAt(0,0,0);
 const aim=new THREE.Vector3(),desired=new THREE.Vector3(),desiredAim=new THREE.Vector3();let mode='first',initialized=false,saveTimer;
 function resize(){const aspect=host.clientWidth/Math.max(1,host.clientHeight),half=2.04;perspective.aspect=aspect;perspective.updateProjectionMatrix();overhead.left=-half*Math.max(1,aspect);overhead.right=-overhead.left;overhead.top=half*Math.max(1,1/aspect);overhead.bottom=-overhead.top;overhead.zoom=settings.zoom;overhead.updateProjectionMatrix();}
 function set(values){settings=sanitizeCamera({...settings,...values});perspective.fov=settings.fov;resize();clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem(STORAGE,JSON.stringify(settings));}catch{}},180);}
 function avoid(position,origin){const delta=position.clone().sub(origin),length=delta.length();if(length<.001)return;const hit=world.castShape(origin,{x:0,y:0,z:0,w:1},delta,new RAPIER.Ball(.055),.005,1,true,undefined,undefined,undefined,undefined,c=>c.parent()===null);if(hit)position.copy(origin).addScaledVector(delta,Math.max(0,hit.time_of_impact-.02/length));}
 return {resize,set,reset:()=>set(CAMERA_DEFAULTS),toggle(){mode=mode==='first'?'chase':mode==='chase'?'top':'first';initialized=false;},get mode(){return mode;},get settings(){return {...settings};},get camera(){return mode==='top'?overhead:perspective;},orbit(dx,dy){if(mode==='first'&&(dx||dy)){set({orbit:Math.atan2(Math.sin(settings.orbit+dx),Math.cos(settings.orbit+dx)),lookPitch:settings.lookPitch-dy});return;}if(mode==='chase'&&(dx||dy))set({orbit:Math.atan2(Math.sin(settings.orbit+dx),Math.cos(settings.orbit+dx)),height:settings.height+dy});},zoom(delta){set(mode==='top'?{zoom:settings.zoom-delta*.001}:mode==='first'?{fov:settings.fov+delta*.015}:{distance:settings.distance+delta*.0015});},update(p,yaw,dt){if(mode==='top')return;if(mode==='first'){const heading=yaw+settings.orbit;perspective.position.set(p.x+Math.sin(yaw)*.075,p.y+settings.eyeHeight,p.z+Math.cos(yaw)*.075);perspective.lookAt(perspective.position.clone().add(new THREE.Vector3(Math.sin(heading)*Math.cos(settings.lookPitch),Math.sin(settings.lookPitch),Math.cos(heading)*Math.cos(settings.lookPitch))));initialized=false;return;}desiredAim.set(p.x,p.y+.09,p.z);const heading=yaw+settings.orbit;desired.set(p.x-Math.sin(heading)*settings.distance,p.y+settings.height,p.z-Math.cos(heading)*settings.distance);avoid(desired,desiredAim);if(!initialized){perspective.position.copy(desired);aim.copy(desiredAim);initialized=true;}else{const blend=1-Math.exp(-dt*9);perspective.position.lerp(desired,blend);aim.lerp(desiredAim,blend);}avoid(perspective.position,aim);perspective.lookAt(aim);},dispose(){clearTimeout(saveTimer);try{localStorage.setItem(STORAGE,JSON.stringify(settings));}catch{}}};
}
