import * as THREE from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import {jawBoxes,jawOffset,JAW_RADIUS,JAW_WIDTH,JAW_ARC,ringInside,RING_GROUP,SOLID_GROUP,JAW_GROUP} from './gripper.js';
import {createMotion,STATION} from './motion.js';
import {createCameras} from './camera.js';
import {readControls,Edges} from './input.js';
import {SIZE,COLORS,POLES,SPIKES,START} from './field.js';

export async function createSimulator(host,onState){
 await RAPIER.init();
 const scene=new THREE.Scene(); scene.background=new THREE.Color('#1b293b');scene.fog=new THREE.Fog('#1b293b',7,18);
 const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2));
 renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
 renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; host.appendChild(renderer.domElement);
 renderer.domElement.setAttribute('aria-label','3D HYPERDRIVE practice field');
 scene.add(new THREE.HemisphereLight(0xcfe7ff,0x34303a,1.45));
 const sun=new THREE.DirectionalLight(0xffedd6,3.2);sun.position.set(-2.3,4.5,-2.8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-3;sun.shadow.camera.right=3;sun.shadow.camera.top=3;sun.shadow.camera.bottom=-3;sun.shadow.camera.near=.1;sun.shadow.camera.far=12;sun.shadow.normalBias=.003;sun.shadow.bias=-.00015;sun.shadow.radius=3;scene.add(sun);
 const fill=new THREE.DirectionalLight(0xb7d8ff,.65);fill.position.set(3,2,3);scene.add(fill);
 const world=new RAPIER.World({x:0,y:-9.81,z:0}); world.timestep=1/60;world.numSolverIterations=8;world.numInternalPgsIterations=2;
 const cameras=createCameras(host,world,RAPIER);
 const material=(color,extra={})=>new THREE.MeshStandardMaterial({color,roughness:.58,...extra});
 function mesh(geo,color,parent=scene){const m=new THREE.Mesh(geo,material(color));m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 function box(x,y,z,w,h,d,color,parent=scene){const m=mesh(new THREE.BoxGeometry(w,h,d),color,parent);m.position.set(x,y,z);return m;}
 function fixedBox(x,y,z,w,h,d,color,kind='obstacle'){const m=box(x,y,z,w,h,d,color);const c=world.createCollider(RAPIER.ColliderDesc.cuboid(w/2,h/2,d/2).setTranslation(x,y,z).setFriction(.7));c.userData={kind};return m;}
 function label(text,x,z,color='#d7e2ed',width=.65){const c=document.createElement('canvas');c.width=512;c.height=80;const ctx=c.getContext('2d');ctx.font='600 35px Arial';ctx.textAlign='center';ctx.fillStyle=color;ctx.fillText(text,256,50);const t=new THREE.CanvasTexture(c);const m=new THREE.Mesh(new THREE.PlaneGeometry(width,width*80/512),new THREE.MeshBasicMaterial({map:t,transparent:true,depthWrite:false,side:THREE.DoubleSide}));m.rotation.x=-Math.PI/2;m.rotation.z=Math.PI;m.position.set(x,.008,z);scene.add(m);return m;}
 fixedBox(0,-.04,0,SIZE,.08,SIZE,0x777e86,'terrain');
 for(let i=0;i<6;i++)for(let j=0;j<6;j++)box(-SIZE/2+(i+.5)*.6096,.001,-SIZE/2+(j+.5)*.6096,.604,.002,.604,(i+j)%2?0x838d98:0x8c96a0).castShadow=false;
 for(const s of [-1,1]){fixedBox(s*SIZE/2,.1143,0,.018,.2286,SIZE,0x303b4a);fixedBox(0,.1143,s*SIZE/2,SIZE,.2286,.018,0x303b4a);}
 function zone(x,z,w,d,color,title){box(x,.004,z,w,.004,d,color).castShadow=false;label(title,x,z,'#ffffff',Math.min(w*.88,.7));}
 function triangle(x,z,sign,color,title){const shape=new THREE.Shape();shape.moveTo(0,0);shape.lineTo(.635*sign,0);shape.lineTo(0,.635*sign);shape.closePath();const m=mesh(new THREE.ShapeGeometry(shape),color);m.material.side=THREE.DoubleSide;m.castShadow=false;m.rotation.x=Math.PI/2;m.position.set(x,.006,z);label(title,x+sign*.19,z+sign*.13,'#ffffff',.31);}
 zone(0,-1.524,1.2192,.6096,0x93283d,'RED START');zone(0,1.524,1.2192,.6096,0x244ba8,'BLUE START');
 triangle(-1.816,-1.816,1,COLORS.red,'DROP');triangle(1.816,1.816,-1,COLORS.blue,'DROP');
 for(const [x,z,s,c] of [[-1.816,1.816,1,COLORS.red],[1.816,-1.816,-1,COLORS.blue]]){const pts=[new THREE.Vector3(x,.009,z-s*.6604),new THREE.Vector3(x+s*.6604,.009,z)];scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:c})));label('SOURCE',x+s*.23,z-s*.13,'#ffffff',.42);}
 for(const p of POLES){const c=COLORS[p.team];const base=mesh(new THREE.CylinderGeometry(.0525,.0525,.016,24),c);base.position.set(p.x,.008,p.z);const post=mesh(new THREE.CylinderGeometry(.0127,.0127,p.height-.016,16),p.type==='STAR'?0xdce3e6:c);post.position.set(p.x,p.height/2,p.z);const cap=mesh(new THREE.SphereGeometry(.018,12,8),c);cap.scale.y=.4;cap.position.set(p.x,p.height,p.z);for(const desc of [RAPIER.ColliderDesc.cylinder(.008,.0525).setTranslation(p.x,.008,p.z),RAPIER.ColliderDesc.cylinder((p.height-.016)/2,.0127).setTranslation(p.x,p.height/2,p.z),RAPIER.ColliderDesc.cylinder(.0072,.018).setTranslation(p.x,p.height,p.z)])world.createCollider(desc).userData={kind:'obstacle'};}
 for(const s of [-1,1]){box(0,.006,s*.6096,1.22,.006,.018,s<0?COLORS.red:COLORS.blue);label('HIGH POLES',0,s*.77,'#e9edf1',.56);label('STAR POLES',0,s*1.25,'#e9edf1',.56);}
 for(const side of [-1,1]){const x=side*1.51,c=side<0?COLORS.red:COLORS.blue;
  fixedBox(x,STATION.height/2,0,.46,STATION.height,STATION.halfLength*2,0x536276,'terrain');
  box(x,STATION.height+.001,0,.40,.002,STATION.halfLength*2,c);label('SPACE STATION',x,0,'#ffffff',.42).position.y=STATION.height+.005;
  for(const sign of [-1,1]){const near=sign*STATION.halfLength,far=sign*(STATION.halfLength+STATION.rampLength),h=STATION.height;const v=new Float32Array([x-.23,0,far,x+.23,0,far,x-.23,0,near,x+.23,0,near,x-.23,h,near,x+.23,h,near]);const idx=[0,1,4,1,5,4,0,4,2,1,3,5,2,4,5,2,5,3,0,2,1,1,2,3];const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(v,3));geo.setIndex(idx);const flatGeo=geo.toNonIndexed();flatGeo.computeVertexNormals();geo.dispose();const ramp=mesh(flatGeo,0xa7b6c4);ramp.material.side=THREE.DoubleSide;world.createCollider(RAPIER.ColliderDesc.convexHull(v).setFriction(.8)).userData={kind:'terrain'};}
  for(const z of [-.3,.3]){const px=x+side*.205;const pole=mesh(new THREE.CylinderGeometry(.0127,.0127,.17,16),c);pole.position.set(px,STATION.height+.085,z);world.createCollider(RAPIER.ColliderDesc.cylinder(.085,.0127).setTranslation(px,STATION.height+.085,z)).userData={kind:'obstacle'};}
  label('APEX',x,.34,'#ffffff',.25).position.y=STATION.height+.005;
 }
 for(const [x,z,c] of [[-1.16,1.71,COLORS.red],[1.16,-1.71,COLORS.blue]]){fixedBox(x,.12,z,.18,.24,.16,c);for(let i=0;i<6;i++){const r=mesh(new THREE.TorusGeometry(.0375,.01,8,24),COLORS.gold);r.rotation.x=Math.PI/2;r.position.set(x,.04+i*.032,z-.10);}label('VAULT',x,z>.0?z-.26:z+.26,'#ffffff',.35);}
 const motion=createMotion(world);
 const robot=new THREE.Group();scene.add(robot);const acrylic=0xc2d8df;
 box(0,.005,0,.235,.018,.27,acrylic,robot);box(0,.09,-.025,.22,.014,.21,acrylic,robot);
 for(const x of [-.095,.095])for(const z of [-.105,.055]){const bolt=mesh(new THREE.CylinderGeometry(.005,.005,.005,12),0x536575,robot);bolt.position.set(x,.100,z);bolt.material.metalness=.75;bolt.material.roughness=.3;}
 for(const x of [-.095,.095])for(const z of [-.095,.065])box(x,.046,z,.009,.08,.009,0xadb8c0,robot);
 box(0,.04,-.035,.105,.034,.075,0x173345,robot);box(.025,.026,-.105,.10,.025,.04,0x252d38,robot);
 const wheels=[];
 for(const x of [-.145,.145])for(const z of [-.092,.092]){const wheelGroup=new THREE.Group();wheelGroup.position.set(x,-.026,z);robot.add(wheelGroup);wheels.push(wheelGroup);const tire=mesh(new THREE.CylinderGeometry(.074,.074,.045,20),0x171c22,wheelGroup);tire.rotation.z=Math.PI/2;tire.material.roughness=.95;const hub=mesh(new THREE.CylinderGeometry(.048,.048,.047,16),0xe4e8dc,wheelGroup);hub.rotation.z=Math.PI/2;hub.material.roughness=.32;hub.material.metalness=.2;for(let i=0;i<10;i++){const a=i*Math.PI/5;const tread=box(0,Math.sin(a)*.074,Math.cos(a)*.074,.048,.012,.02,0x303740,wheelGroup);tread.rotation.x=-a;}}
 for(const x of [-.093,.093])box(x,.035,.105,.056,.075,.009,COLORS.red,robot);
 const arm=new THREE.Group();arm.position.set(0,0,.065);robot.add(arm);for(const x of [-.035,.035])box(x,0,.105,.014,.018,.21,acrylic,arm);box(0,0,.015,.062,.037,.04,0x245ea5,arm);box(0,0,.215,.055,.035,.04,0x245ea5,arm);
 const claw=new THREE.Group();scene.add(claw);
 const jawMaterial=material(0xbddce5,{roughness:.26,metalness:.12,transparent:true,opacity:.86});
 box(0,0,-.076,.13,.018,.012,0x273c4b,claw);
 const jaws=[-1,1].map(side=>{const group=new THREE.Group();claw.add(group);const shape=new THREE.Shape(),outer=JAW_RADIUS+JAW_WIDTH/2,inner=JAW_RADIUS-JAW_WIDTH/2;for(let i=0;i<=32;i++){const a=-JAW_ARC+2*JAW_ARC*i/32;const x=side*outer*Math.cos(a),z=outer*Math.sin(a);if(i===0)shape.moveTo(x,z);else shape.lineTo(x,z);}for(let i=32;i>=0;i--){const a=-JAW_ARC+2*JAW_ARC*i/32;shape.lineTo(side*inner*Math.cos(a),inner*Math.sin(a));}shape.closePath();const geometry=new THREE.ExtrudeGeometry(shape,{depth:.014,bevelEnabled:true,bevelThickness:.002,bevelSize:.001,bevelSegments:2,steps:1});geometry.rotateX(Math.PI/2);geometry.translate(0,.007,0);const plate=new THREE.Mesh(geometry,jawMaterial);plate.castShadow=true;group.add(plate);const pivot=mesh(new THREE.CylinderGeometry(.009,.009,.020,16),0x778993,group);pivot.position.set(side*.027,0,-.052);const screw=mesh(new THREE.CylinderGeometry(.004,.004,.022,12),0xe3e9ed,group);screw.position.copy(pivot.position);const link=box(side*.025,.014,-.064,.018,.008,.030,0x647d88,group);link.rotation.y=side*.2;return group;});
 const jawBodies=jawBoxes(false).map(b=>{const rb=world.createRigidBody(RAPIER.RigidBodyDesc.kinematicPositionBased());world.createCollider(RAPIER.ColliderDesc.cuboid(b.hx,b.hy,b.hz).setFriction(.22).setCollisionGroups(JAW_GROUP),rb);return rb;});
 world.forEachCollider(c=>{if(c.parent()===null)c.setCollisionGroups(SOLID_GROUP);});
 let closed=false,held=null;
 function syncJaws(immediate=false){const parts=motion.parts(undefined,undefined,undefined,closed,held).jawPieces;parts.forEach((part,i)=>{const rb=jawBodies[i];if(immediate){rb.setTranslation(part.position,true);rb.setRotation(part.rotation,true);}rb.setNextKinematicTranslation(part.position);rb.setNextKinematicRotation(part.rotation);});}
 const target=mesh(new THREE.RingGeometry(.055,.06,32),0x9dfbe8);target.rotation.x=-Math.PI/2;target.position.y=.011;target.material=new THREE.MeshBasicMaterial({color:0x96ffe3,side:THREE.DoubleSide,transparent:true,opacity:.9});
 const ringGeometry=new THREE.TorusGeometry(.0375,.01,10,32);ringGeometry.rotateX(Math.PI/2);ringGeometry.scale(1,1.5,1);
 const cores=[];
 function addCore(x,z,team){const rb=world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(x,.035,z).setLinearDamping(.12).setAngularDamping(.25).setCcdEnabled(true));rb.setEnabledRotations(false,true,false,true);for(let i=0;i<12;i++){const a=i*Math.PI/6;world.createCollider(RAPIER.ColliderDesc.cuboid(.011,.015,.010).setTranslation(Math.cos(a)*.0375,0,Math.sin(a)*.0375).setRotation({x:0,y:Math.sin(-a/2),z:0,w:Math.cos(-a/2)}).setMass(.04/12).setFriction(.18).setFrictionCombineRule(RAPIER.CoefficientCombineRule.Min).setRestitution(.08).setCollisionGroups(RING_GROUP),rb);}const m=mesh(ringGeometry,COLORS[team]);m.material.roughness=.3;m.material.metalness=.03;cores.push({body:rb,mesh:m,team,start:{x,z}});}
 SPIKES.forEach(p=>addCore(p.x,p.z,p.team));addCore(0,-1.13,'red');for(const [x,z] of [[-1.64,1.62],[-1.46,1.62],[-1.63,1.43]])addCore(x,z,'red');
 let paused=false,disposed=false,raf,accum=0,last=performance.now(),lastHud=0,message='Lower the open jaws around a RED CORE, then close with F / X.',pickups=0,drops=0;
 const keys=new Set(),edges=new Edges(),commands=[];let input=readControls(keys,[]),candidate=null;const clawPosition=new THREE.Vector3();
 function updateRobot(state=motion.state){robot.position.copy(state.position);robot.rotation.set(state.pitch,state.yaw,state.roll,'YXZ');arm.rotation.x=-state.angle;const layout=motion.parts(state.position,state.yaw,state.angle,closed,held,{pitch:state.pitch,roll:state.roll});claw.position.copy(layout.claw);claw.quaternion.copy(layout.clawRotation);jaws.forEach((jaw,i)=>jaw.position.x=(i===0?-1:1)*jawOffset(closed));wheels.forEach((wheel,i)=>wheel.rotation.x=state.wheelAngles[i]);robot.updateMatrixWorld(true);claw.updateMatrixWorld(true);clawPosition.copy(layout.claw);}
 function available(){return cores.filter(c=>c.team!=='blue'&&ringInside(clawPosition,c.body.translation(),motion.state.yaw)&&motion.ringClear(c.body.translation(),clawPosition)).sort((a,b)=>clawPosition.distanceTo(a.body.translation())-clawPosition.distanceTo(b.body.translation()))[0];}
 function tryPickup(){if(held||!closed)return;const nearby=available();if(!nearby)return;held=nearby;held.body.setBodyType(RAPIER.RigidBodyType.KinematicPositionBased,true);for(let i=0;i<held.body.numColliders();i++)held.body.collider(i).setCollisionGroups(0);held.body.setTranslation(clawPosition,true);pickups++;message='CORE secured. E / R2 to lift; G / Circle to drop.';}
 function release(){if(!held)return;for(let i=0;i<held.body.numColliders();i++)held.body.collider(i).setCollisionGroups(RING_GROUP);held.body.setBodyType(RAPIER.RigidBodyType.Dynamic,true);held.body.setTranslation(clawPosition,true);held.body.setLinvel({x:0,y:0,z:0},true);held.body.setAngvel({x:0,y:0,z:0},true);held=null;drops++;message='CORE released.';}
 function recover(){updateRobot();release();motion.reset();closed=false;syncJaws(true);message='Robot returned to start.';}
 function reset(){recover();for(const c of cores){c.body.setBodyType(RAPIER.RigidBodyType.Dynamic,true);c.body.setTranslation({x:c.start.x,y:.035,z:c.start.z},true);c.body.setLinvel({x:0,y:0,z:0},true);c.body.setAngvel({x:0,y:0,z:0},true);c.body.setRotation({x:0,y:0,z:0,w:1},true);}pickups=0;drops=0;message='Field reset. Practice CORE straight ahead.';}
 function action(name){if(name==='pause'){paused=!paused;keys.clear();return;}if(name==='camera'){cameras.toggle();return;}if(name==='cameraReset'){cameras.reset();return;}if(paused)return;if(name==='reset')reset();if(name==='recover')recover();if(name==='drop'){if(motion.canClose(false,held)){closed=false;release();}else message='Claw blocked. Move away before opening.';}if(name==='grab'){if(!motion.canClose(!closed,held)){message='Claw blocked by a solid object.';return;}closed=!closed;if(!closed)release();else{tryPickup();if(!held)message='Empty claw. Open it, surround the ring, then close.';}}}
 const keydown=e=>{if(e.target.closest?.('button,input,select,textarea'))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();const discrete={KeyP:'pause',KeyF:'grab',KeyG:'drop',KeyT:'recover',KeyR:'reset',KeyC:'camera'};if(discrete[e.code]){if(!e.repeat)commands.push(discrete[e.code]);return;}keys.add(e.code);};
 const keyup=e=>keys.delete(e.code);const blur=()=>{keys.clear();paused=true;};const visibility=()=>{if(document.hidden)blur();};
 window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility);
 const canvas=renderer.domElement;let drag=null;
 const pointerdown=e=>{if(e.button===2){drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);e.preventDefault();}};const pointermove=e=>{if(drag){cameras.orbit(-(e.clientX-drag.x)*.006,(e.clientY-drag.y)*.006);drag={x:e.clientX,y:e.clientY};}};const pointerup=()=>{drag=null;};const context=e=>e.preventDefault();const wheel=e=>{e.preventDefault();cameras.zoom(e.deltaY);};
 canvas.addEventListener('pointerdown',pointerdown);canvas.addEventListener('pointermove',pointermove);canvas.addEventListener('pointerup',pointerup);canvas.addEventListener('pointercancel',pointerup);canvas.addEventListener('lostpointercapture',pointerup);canvas.addEventListener('contextmenu',context);canvas.addEventListener('wheel',wheel,{passive:false});
 function resize(){renderer.setSize(host.clientWidth,host.clientHeight);cameras.resize();}const observer=new ResizeObserver(resize);observer.observe(host);resize();
 const snapshot=()=>({ready:true,blocked:motion.state.blocked,cameraSettings:cameras.settings,controller:input.controller,connected:input.connected,arm:Math.round(motion.state.angle*180/Math.PI),grabber:closed?'CLOSED':'OPEN',held:held?held.team.toUpperCase():'EMPTY',pickups,drops,paused,mode:cameras.mode,message,near:!!candidate});
 function tick(controls){motion.step(controls,1/60,closed,held);updateRobot();syncJaws();if(held)held.body.setNextKinematicTranslation(clawPosition);world.step();}
 function frame(now){if(disposed)return;raf=requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.08);last=now;let pads=[];try{pads=navigator.getGamepads?.()||[];}catch{}input=readControls(keys,pads);updateRobot();for(const name of ['grab','drop','recover','reset','camera'])if(edges.take(input,name))commands.push(name);while(commands.length)action(commands.shift());if(!paused){cameras.orbit(-input.lookX*dt*1.7,input.lookY*dt);accum+=dt;while(accum>=1/60){tick(input);accum-=1/60;}}else accum=0;updateRobot(motion.render(paused?1:accum/(1/60)));candidate=held||closed?null:available();target.position.set(clawPosition.x,motion.terrainHeight(clawPosition.x,clawPosition.z)+.011,clawPosition.z);target.material.color.setHex(candidate?0x79ffad:0xffffff);target.visible=!held;for(const c of cores){c.mesh.position.copy(c.body.translation());c.mesh.quaternion.copy(c.body.rotation());}if(held)held.mesh.position.copy(clawPosition);cameras.update(robot.position,robot.rotation.y,dt);renderer.render(scene,cameras.camera);if(now-lastHud>90){onState(snapshot());lastHud=now;}}
 syncJaws(true);world.step();updateRobot();raf=requestAnimationFrame(frame);
 return {command:name=>commands.push(name),setCamera:values=>cameras.set(values),snapshot,dispose(){disposed=true;cancelAnimationFrame(raf);observer.disconnect();window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);canvas.removeEventListener('pointerdown',pointerdown);canvas.removeEventListener('pointermove',pointermove);canvas.removeEventListener('pointerup',pointerup);canvas.removeEventListener('pointercancel',pointerup);canvas.removeEventListener('lostpointercapture',pointerup);canvas.removeEventListener('contextmenu',context);canvas.removeEventListener('wheel',wheel);cameras.dispose();scene.traverse(o=>{o.geometry?.dispose();if(o.material){o.material.map?.dispose();o.material.dispose();}});renderer.dispose();world.free();canvas.remove();}};
}
